site_name: MkDocs CWTS Template
site_url: https://andrebrasil.github.io/mkdocs/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  logo: assets/cwts_logo_white_alone.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
      primary: indigo
      accent: indigo 
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
      primary: indigo
      accent: indigo

nav:
- Home: index.md
- Notebook page: demo-nb.ipynb
- Python file: demo-script.py
- MD Example: demo-md.md
- Page 2: page2.md

plugins:
    - search: {}    
    - social
    - mkdocs-jupyter 

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Portuguese
      link: /pt/
      lang: pt-br    
    
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/andre-brasil”  target="_blank" rel="noopener">André Brasil</a>
